In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],'max_features': ['auto','sqrt','log2'],
'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
grid.fit(X_train, y_train)

C:\Users\sony\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 18 candidates, totalling 54 fits

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    5.3s
[Parallel(n_jobs=-1)]: Done  47 out of  54 | elapsed:    5.5s remaining:    0.7s
[Parallel(n_jobs=-1)]: Done  54 out of  54 | elapsed:    5.5s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [12]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'mae', 'max_features': 'auto', 'splitter': 'random'}:

In [13]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008074,0.004349,0.009415,0.000961,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.528935,0.683961,0.691914,0.634818,0.075066,6
1,0.003364,0.003418,0.006717,0.003412,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.584333,0.647087,0.686113,0.639116,0.041943,4
2,0.008714,0.000960,0.004722,0.003799,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.577519,0.374025,0.658476,0.536719,0.119605,16
3,0.007390,0.003787,0.005373,0.003799,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.433239,0.546467,0.594342,0.524580,0.067581,17
4,0.010078,0.008233,0.006734,0.004762,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.543294,0.697914,0.752401,0.664400,0.088614,2
5,0.006757,0.003446,0.006743,0.003429,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.573747,0.601024,0.644213,0.606291,0.029015,10
6,0.042999,0.005298,0.004044,0.004357,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.667102,0.637482,0.679692,0.661432,0.017685,3
7,0.033616,0.004735,0.003355,0.003413,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.650323,0.675810,0.687636,0.671233,0.015576,1
8,0.029551,0.006632,0.004723,0.003794,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.645706,0.559612,0.563258,0.589588,0.039776,11
9,0.026195,0.005709,0.003366,0.003416,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.559968,0.685436,0.582354,0.609197,0.054634,8
10,0.024234,0.005768,0.010082,0.000013,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.568694,0.576844,0.503354,0.549652,0.032879,15
11,0.022919,0.003825,0.004038,0.004353,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.574758,0.626510,0.545048,0.582097,0.033642,13
12,0.007395,0.003790,0.003371,0.004767,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.527420,0.677953,0.703420,0.636142,0.077706,5
13,0.006049,0.004361,0.006715,0.003411,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.587150,0.628866,0.639373,0.618428,0.022565,7
14,0.006737,0.004764,0.006037,0.004348,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.558699,0.677568,0.588581,0.608227,0.050487,9
15,0.004044,0.004362,0.003355,0.004744,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.606760,0.550716,0.604077,0.587206,0.025804,12
16,0.009401,0.000968,0.003357,0.003414,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.628152,0.547211,0.492745,0.556117,0.055652,14
17,0.006721,0.004752,0.003362,0.004754,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.541831,0.501719,0.522083,0.521900,0.016381,18

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:55
BMI:33
Children:4
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [15]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[63770.42801]